name: calculator-collection
description: Mojo로 구현한 한국 실업급여 계산기 허브
version: 0.1.0
created: 2026-01-27
last_modified: 2026-01-27

tech_stack:
  language: Mojo
  version: 24.5+
  dependencies:
    - Python 3.8+ (for input/output)

structure:
  src:
    - unemployment_calculator/
      - types.mojo (데이터 구조 정의)
      - utils.mojo (유틸리티 함수)
      - calculator.mojo (계산 로직)
      - main.mojo (REPL 인터페이스)
  tests:
    - (향후 추가 예정)
  docs:
    - README.md
    - HISTORY.md

implemented_features:
  - 일반 근로자 실업급여 계산
  - 일용 근로자 실업급여 계산
  - 자영업자 실업급여 계산
  - REPL 대화형 인터페이스
  - 나이/가입기간별 지급일수 자동 계산
  - 상한액/하한액 자동 적용

regulations:
  base: 한국 고용보험법
  reference_url: https://eiac.ei.go.kr/ei/m/pf/MOW-PF-00-180-C.html
  benefit_rate: 60% (2019년 10월 1일 이후)
  daily_upper_limit: 66000원
  daily_lower_limit: 최저임금 80% × 8시간
  minimum_insurance_period: 180일

todo:
  high_priority:
    - 단위 테스트 추가
    - 입력 유효성 검증 강화
    - 날짜 계산 정확도 개선
  medium_priority:
    - CLI 배치 모드 추가
    - 결과 저장 기능 (CSV, JSON)
    - 2019년 이전 규정 지원
  low_priority:
    - 다국어 지원
    - 웹 인터페이스 추가
    - 다른 계산기 추가 (퇴직금, 연차수당 등)

development_notes:
  - Mojo의 struct는 pass-by-value이므로 주의
  - Python 상호운용성을 위해 Python 모듈 import 사용
  - 날짜 계산은 현재 근사치 (월=30일 가정)
  - 기준보수 등급 금액은 예시 값 (실제 규정 확인 필요)

contact:
  project_path: /Users/hyebin/Documents/DEV_PROJECT/calculator-collection
  git_initialized: true
  moai_framework: enabled
